name: Deploy to Render (on CI success)

on:
  workflow_run:
    workflows: ["CI (Vitest)"] # must match the name: in ci.yml
    types: [completed]
    branches: [master]

concurrency:
  group: "render-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$HOOK" ]; then
            echo "Missing RENDER_DEPLOY_HOOK_URL secret"; exit 1;
          fi
          curl -fsSL "$HOOK"
